from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from src.utils.config import PROJECT_ROOT


PRODUCTION_PATH_PREFIXES = ("Dockerfile", "docker-compose", "config/production", "src/deploy", "release/")


class GitSafetyAnalyzer:
    def __init__(self, root: str | Path = PROJECT_ROOT) -> None:
        self.root = Path(root).resolve(strict=False)

    def status(self) -> dict[str, Any]:
        output = self._git(["status", "--short"])
        entries = self.parse_status(output.get("stdout", ""))
        return {
            "ok": output.get("ok", False),
            "raw": output.get("stdout", "") or output.get("stderr", ""),
            "entries": entries,
            "untracked": [item for item in entries if item["status"] == "untracked"],
            "modified": [item for item in entries if item["status"] == "modified"],
            "added": [item for item in entries if item["status"] == "added"],
            "deleted": [item for item in entries if item["status"] == "deleted"],
            "renamed": [item for item in entries if item["status"] == "renamed"],
            "production_changes": [item for item in entries if self.requires_approval(item["path"])],
            "protected_existing_changes": [item for item in entries if item["status"] != "untracked"],
        }

    def safe_diff_preview(self, paths: list[str] | None = None, max_chars: int = 20000) -> dict[str, Any]:
        command = ["diff", "--"] + (paths or [])
        output = self._git(command, timeout=30)
        content = output.get("stdout", "") if output.get("ok") else output.get("stderr", "")
        return {
            "ok": output.get("ok", False),
            "content": content[:max_chars],
            "truncated": len(content) > max_chars,
            "paths": paths or [],
            "message": "Diff preview only; existing uncommitted changes are not modified.",
        }

    def commit_message(self, issue: dict[str, Any] | str, files: list[str] | None = None) -> dict[str, Any]:
        if isinstance(issue, dict):
            title = str(issue.get("title") or issue.get("message") or "improve AIOS coding engine")
            risk = str(issue.get("risk", "medium"))
        else:
            title = str(issue)
            risk = "medium"
        prefix = "fix(coding-engine)" if any(token in title.lower() for token in ("fix", "fail", "error", "失敗")) else "chore(coding-engine)"
        if any(token in title.lower() for token in ("revenue", "roi", "収益", "初収益")):
            prefix = "feat(revenue)"
        subject = f"{prefix}: {self._shorten(title, 58)}"
        return {
            "subject": subject,
            "body": "\n".join(
                [
                    self._shorten(title, 400),
                    "",
                    f"Risk: {risk}",
                    f"Files: {', '.join((files or [])[:12])}",
                    "Generated by AIOS Coding Engine Phase11.5.",
                ]
            ).strip(),
            "files": files or [],
        }

    def parse_status(self, status_text: str) -> list[dict[str, Any]]:
        entries = []
        for line in status_text.splitlines():
            if not line.strip():
                continue
            code = line[:2]
            path = line[3:].strip().strip('"')
            status = self._classify_status(code)
            entries.append(
                {
                    "code": code,
                    "path": path,
                    "status": status,
                    "category": self._category(path),
                    "requires_approval": self.requires_approval(path),
                }
            )
        return entries

    def requires_approval(self, path: str) -> bool:
        normalized = path.replace("\\", "/")
        return normalized.startswith(PRODUCTION_PATH_PREFIXES) or normalized in {".env", ".env.example"}

    def _git(self, args: list[str], timeout: int = 15) -> dict[str, Any]:
        try:
            completed = subprocess.run(
                ["git", *args],
                cwd=str(self.root),
                capture_output=True,
                text=True,
                timeout=timeout,
                shell=False,
            )
            return {
                "ok": completed.returncode == 0,
                "stdout": completed.stdout,
                "stderr": completed.stderr,
                "exit_code": completed.returncode,
            }
        except Exception as exc:
            return {"ok": False, "stdout": "", "stderr": str(exc), "exit_code": 1}

    @staticmethod
    def _classify_status(code: str) -> str:
        if code == "??":
            return "untracked"
        if "D" in code:
            return "deleted"
        if "R" in code:
            return "renamed"
        if "A" in code:
            return "added"
        if "M" in code:
            return "modified"
        return "other"

    @staticmethod
    def _category(path: str) -> str:
        suffix = Path(path).suffix.lower()
        if path.startswith("tests/") or path.startswith("tests\\"):
            return "test"
        if path.startswith("pages/") or path.startswith("pages\\"):
            return "ui"
        if path.startswith("config/") or path.startswith("config\\"):
            return "config"
        if suffix in {".md", ".txt"}:
            return "docs"
        if suffix == ".py":
            return "python"
        return "asset"

    @staticmethod
    def _shorten(text: str, limit: int) -> str:
        compact = " ".join(text.split())
        return compact if len(compact) <= limit else compact[: max(limit - 3, 1)].rstrip() + "..."
