"""Daily Report Generator — creates markdown reports from KPI, tasks, and finance data."""
from datetime import date
from pathlib import Path


def generate_report(kpi_data: dict, tasks_data: dict, finance_data: dict, ceo_message: str) -> str:
    today = date.today()
    date_str = today.strftime("%Y年%m月%d日")

    tasks = tasks_data.get("tasks", [])
    done_tasks = [t for t in tasks if t["status"] == "done"]
    remaining_tasks = [t for t in tasks if t["status"] != "done"]
    in_progress = [t for t in tasks if t["status"] == "in_progress"]
    total = len(tasks)
    done_count = len(done_tasks)
    pct = int(done_count / total * 100) if total > 0 else 0

    targets = kpi_data.get("targets", {})
    actuals = kpi_data.get("actuals", {})

    today_rev = finance_data.get("today", {}).get("revenue", 0)
    month_rev = finance_data.get("month", {}).get("revenue", 0)
    month_exp = finance_data.get("month", {}).get("expense", 0)
    month_profit = month_rev - month_exp
    breakeven = finance_data.get("month", {}).get("breakeven", 0)
    breakeven_remaining = max(0, breakeven - month_rev)
    roi = (month_profit / month_exp * 100) if month_exp > 0 else 0.0

    lines = [
        f"# Creator Factory OS — 日次レポート",
        f"**日付:** {date_str}  |  **バージョン:** v4.2 Dashboard Factory",
        "",
        "---",
        "",
        "## 📊 KPI進捗",
        "",
        f"| 指標 | 目標 | 実績 | 達成率 |",
        f"|------|------|------|--------|",
        f"| 今日の売上目標 | ¥{targets.get('sales_target', 0):,} | ¥{actuals.get('sales_actual', 0):,} | {_pct(actuals.get('sales_actual',0), targets.get('sales_target',1))}% |",
        f"| note投稿数 | {targets.get('note_posts',0)}件 | {actuals.get('note_posts',0)}件 | {_pct(actuals.get('note_posts',0), targets.get('note_posts',1))}% |",
        f"| 動画制作数 | {targets.get('video_count',0)}本 | {actuals.get('video_count',0)}本 | {_pct(actuals.get('video_count',0), targets.get('video_count',1))}% |",
        f"| SNS投稿数 | {targets.get('sns_posts',0)}件 | {actuals.get('sns_posts',0)}件 | {_pct(actuals.get('sns_posts',0), targets.get('sns_posts',1))}% |",
        f"| 営業件数 | {targets.get('sales_calls',0)}件 | {actuals.get('sales_calls',0)}件 | {_pct(actuals.get('sales_calls',0), targets.get('sales_calls',1))}% |",
        f"| 開発タスク数 | {targets.get('dev_tasks',0)}件 | {actuals.get('dev_tasks',0)}件 | {_pct(actuals.get('dev_tasks',0), targets.get('dev_tasks',1))}% |",
        "",
        "---",
        "",
        f"## ✅ 完了タスク ({done_count}/{total} — {pct}%)",
        "",
    ]

    if done_tasks:
        for t in done_tasks:
            lines.append(f"- [x] [{t['category']}] {t['title']}")
    else:
        lines.append("- (完了タスクなし)")

    lines += [
        "",
        f"## 🔄 進行中タスク ({len(in_progress)}件)",
        "",
    ]
    if in_progress:
        for t in in_progress:
            lines.append(f"- [ ] [{t['category']}] 🔄 {t['title']}")
    else:
        lines.append("- (進行中タスクなし)")

    lines += [
        "",
        f"## ⏸ 残タスク ({len([t for t in remaining_tasks if t['status'] == 'pending'])}件)",
        "",
    ]
    pending = [t for t in remaining_tasks if t["status"] == "pending"]
    if pending:
        for t in pending:
            priority_mark = "🔴" if t["priority"] == "high" else ("🟡" if t["priority"] == "medium" else "🟢")
            lines.append(f"- [ ] [{t['category']}] {priority_mark} {t['title']}")
    else:
        lines.append("- (残タスクなし)")

    lines += [
        "",
        "---",
        "",
        "## 💰 財務サマリー",
        "",
        f"| 項目 | 金額 |",
        f"|------|------|",
        f"| 今日の売上 | ¥{today_rev:,} |",
        f"| 今月売上 | ¥{month_rev:,} |",
        f"| 今月費用 | ¥{month_exp:,} |",
        f"| 今月利益 | ¥{month_profit:,} |",
        f"| ROI | {roi:.1f}% |",
        f"| 損益分岐点まで | ¥{breakeven_remaining:,} |",
        "",
        "---",
        "",
        "## 🤖 AI CEO メッセージ",
        "",
        f"> {ceo_message}",
        "",
        "---",
        "",
        f"*Generated by Creator Factory OS v4.2 — {date.today().isoformat()}*",
    ]

    return "\n".join(lines)


def _pct(actual: int | float, target: int | float) -> int:
    return min(int(actual / target * 100), 100) if target > 0 else 0


def export_report(content: str) -> Path:
    today = date.today().isoformat()
    reports_dir = Path(__file__).parent.parent.parent / "reports" / "daily"
    reports_dir.mkdir(parents=True, exist_ok=True)
    out_path = reports_dir / f"{today}_daily_report.md"
    out_path.write_text(content, encoding="utf-8")
    return out_path
